# Generated by Django 5.2.4 on 2025-08-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок",
                        max_length=100,
                        verbose_name="заголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="содержимое блога",
                        null=True,
                        verbose_name="содержимое",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="превью (изображение) блога",
                        null=True,
                        upload_to="blog/preview",
                        verbose_name="превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="дата создания"),
                ),
                (
                    "publication",
                    models.BooleanField(
                        help_text="Проставьте признак публикации",
                        verbose_name="признак публикации",
                    ),
                ),
                (
                    "views",
                    models.CharField(
                        help_text="количество просмотров",
                        verbose_name="количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
