# Generated by Django 5.2.4 on 2025-08-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views",
            field=models.IntegerField(
                blank=True,
                help_text="количество просмотров",
                null=True,
                verbose_name="количество просмотров",
            ),
        ),
    ]
